import type { NextPage } from "next";
import Head from "next/head";
import Authenticated from "src/components/Authenticated";
import GET_Query from "src/components/graphql/GET_Query";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Authenticated />

      <GET_Query />
    </div>
  );
};

export default Home;
