import type { NextPage } from "next";
import Head from "next/head";
import Authenticated from "src/components/Authenticated";
import SingOut from "src/components/SingOut";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Authenticated />

      <h1>d</h1>

      <div className="text-center">
        <SingOut />
      </div>
    </div>
  );
};

export default Home;
